module gen_pll_rpll (
    input  logic clkin,   // 27 MHz osc on TangConsole
    output logic clk_sys, // 148.5 MHz  (for HDMI ×2)
    output logic clk_pix, // 74.25 MHz  (HDMI pixel clock)
    output logic clk_cpu, // 12.000 MHz
    output logic locked
);
    // Gowin IP wrapper generated by IDE:
    //   clkin: 27 MHz
    //   clkout0: 148.5 MHz  (IDIV_SEL=0, FBDIV_SEL=10, ODIV_SEL=4) -> 27*11/2 = 148.5
    //   clkout1: 74.25 MHz  (IDIV_SEL=0, FBDIV_SEL=10, ODIV_SEL=8) -> 27*11/4 = 74.25 (Used DIVIDER1)
    //   clkout2: 12.000 MHz (IDIV_SEL=8, FBDIV_SEL=7, ODIV_SEL=4) -> 27/9*8/2 = 12 (Used DIVIDER2)
    //   duty = 50%, phase = 0
    // Paste the auto‑generated `rPLL` instance here
    // Example (Replace with actual generated code):
    /*
    rPLL rpll_inst (
        .CLKIN(clkin),
        .CLKOUT(clk_sys),    // CLKOUT0
        .CLKOUTD(clk_pix),   // CLKOUTD (uses DIVIDER1)
        .CLKOUTD3(clk_cpu),  // CLKOUTD3 (uses DIVIDER2)
        .RESET(1'b0),       // Assuming no external reset needed for PLL
        .RESET_P(1'b0),
        .LOCK(locked)
        // Connect other ports if needed (FBOUT, CLKOUTP, etc.)
    );
    */

    // Placeholder assignments until IP is generated
    assign clk_sys = clkin;
    assign clk_pix = clkin;
    assign clk_cpu = clkin;
    assign locked = 1'b1;

endmodule 